#!/bin/bash
# Complete Workflow Guide

echo ""
echo "=========================================="
echo "  PDF Text Extraction - Complete Workflow"
echo "=========================================="
echo ""
echo "✅ What's Working:"
echo "   • Footer cropping (350px removed)"
echo "   • 3-column layout handling"
echo "   • Document cleaning & splitting"
echo "   • Reference number detection"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Extract Text from PDFs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "python extract_text.py --year 2014 --limit 2"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Clean & Split Documents"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "python clean_and_split.py --batch extracted_text/2014/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Reference Pattern: 2014G02943SRLB1"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  SRLB = SARL    SANB = SA    FCCC = Fonds de Commerce"
echo ""
echo "📊 Current Stats: 522 documents from 3 journals"
echo ""
echo "=========================================="
echo ""
